import {Product} from './Product';
export var productList: Product[] = [
    {"id": 1, "name": "juice 1", "description": "description 1"},
    {"id": 2, "name": "juice 2", "description": "description 2"},
    {"id": 3, "name": "juice 3", "description": "description 3"},
    {"id": 4, "name": "juice 4", "description": "description 4"},
    {"id": 5, "name": "juice 5", "description": "description 5"},
    {"id": 6, "name": "juice 6", "description": "description 6"},
    {"id": 7, "name": "juice 7", "description": "description 7"},
    {"id": 8, "name": "juice 8", "description": "description 8"},
    {"id": 9, "name": "juice 9", "description": "description 9"},
    {"id": 10, "name": "orange 1", "description": "description 1"},
    {"id": 11, "name": "orange 2", "description": "description 2"},
    {"id": 12, "name": "orange 3", "description": "description 3"},
    {"id": 13, "name": "orange 4", "description": "description 4"},
    {"id": 14, "name": "orange 5", "description": "description 5"},
    {"id": 15, "name": "orange 6", "description": "description 6"},
    {"id": 16, "name": "orange 7", "description": "description 7"},
    {"id": 17, "name": "orange 8", "description": "description 8"},
    {"id": 18, "name": "orange 9", "description": "description 9"},
    {"id": 19, "name": "orange 10", "description": "description 10"},
    {"id": 20, "name": "orange 11", "description": "description 11"},
    {"id": 21, "name": "orange 12", "description": "description 12"},
    {"id": 22, "name": "orange 13", "description": "description 13"},
    {"id": 23, "name": "orange 14", "description": "description 14"},
    {"id": 24, "name": "orange 15", "description": "description 15"},
    {"id": 25, "name": "orange 16", "description": "description 16"},
    {"id": 26, "name": "orange 17", "description": "description 17"},
]